name: Quality

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: lint
        run: yarn lint

  typescript-compatibility:
    name: types w/ ${{ matrix.typescript-scenario }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        typescript-scenario:
          - typescript@4.2
          - typescript@4.3
          - typescript@4.4
          - typescript@4.5
          - typescript@4.6
          - typescript@next
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Update TS Version
        run: yarn add --dev ${{ matrix.typescript-scenario }}
        working-directory: test-app
      - name: Type checking
        run: yarn tsc --build
        working-directory: test-app

